4.12 rebase
ocaml-flambda/ocaml pull request #418
Opened 2021-04-26 12:18 UTC by poechsel

Draft PR to rebase flambda2 on top of OCaml 4.12. 

It's currently not compiling and is not meant to be reviewed yet.

2021-05-26 12:57 UTC, mshinwell requested changes

2021-05-26 12:57 UTC, mshinwell commented on asmcomp/cmm.mli
> -      (** The [machtype] is the machine type of the result.
Looks like this comment has been lost

2021-05-26 12:57 UTC, mshinwell commented on middle_end/closure/closure.ml
>     replace it by an integer constant *)
I think this is the wrong resolution (likewise for lines 801/802 above).  We should be removing the "or Value_constptr" phrase.

2021-05-26 12:57 UTC, mshinwell commented on middle_end/closure/closure.ml
> +      close env       (Lapply{ap_loc=loc;
Bad formatting

2021-05-26 12:57 UTC, mshinwell commented on middle_end/closure/closure.ml
> +      close env       (Lapply{ap_loc=loc;
(in fact I'm not sure there should be any change here at all)

2021-05-26 12:57 UTC, mshinwell commented on middle_end/flambda/to_cmm/un_cps_helper.ml
> +  | Fabricated -> Misc.fatal_error "[Fabricated] king not expected here"
king -> kind

2021-05-26 12:57 UTC, mshinwell commented on middle_end/flambda/to_cmm/un_cps_helper.mli
> +val  exttype_of_kind : Flambda_kind.t -> Cmm.exttype
Double space after "val"

2021-05-26 12:57 UTC, mshinwell commented on runtime/compact.c
> +
Unnecessary change

2021-05-26 12:57 UTC, mshinwell commented
A few minor things to fix.  Then please try building Coq with this PR.  (I'm not sure exactly which version of Coq is needed, but I believe there does exist one that supports OCaml 4.12.)

2021-05-26 13:33 UTC, poechsel commented on middle_end/closure/closure.ml
>     replace it by an integer constant *)
My bad, I forgot to edit the comments when removing Value_constptr

2021-05-26 13:35 UTC, poechsel commented
Coq is building successfully with this PR.

2021-05-26 14:13 UTC, lthls commented
Out of curiosity, why did you need to remove the comparison of bytecode programs in `ocamltest` ? I'd not expect that to be necessary.

2021-05-26 14:39 UTC, poechsel commented
Some tests were failing on the comparison of bytecode programs. Upon closer inspection we noticed that the bytecode was identical at the exception of the digests for one cmi file. We then looked at the cmi files generated using ocamlc.opt and ocamlc.byte and noticed that their content were identical, but when was marshalled one of {ocamlc.opt, ocamlc.byte} was sharing more things than the other one, thus leading to the test failing. We were not able to find the root cause causing the discrepancies in sharing so we decided to deactivate them as was done in https://github.com/ocaml/ocaml/pull/9677

2021-05-27 13:37 UTC, mshinwell approved these changes

2021-05-27 14:50 UTC, merged

2021-05-28 07:52 UTC, Gbury commented
This PR seems to have brought the "stale issue" bot from upstream, was that intended ?

2021-05-28 08:26 UTC, poechsel commented
Not really