Add Rec_info constructor to Named.t
ocaml-flambda/ocaml pull request #434
Opened 2021-05-06 19:18 UTC by lukemaurer

This allows binding a `Rec_info_expr` to a depth variable.

2021-05-06 19:21 UTC, lukemaurer commented
*sigh* There's really no good way to have this depend on both the `depth-parameters` patch and the `rec-info-exprs` patch. Only the last commit is actually supposed to be the PR.

2021-05-17 14:32 UTC, mshinwell requested changes

2021-05-17 14:32 UTC, mshinwell commented on middle_end/flambda/simplify/expr_builder.ml
> +        Name_mode.Or_absent.present Name_mode.normal
We also need another change below: `will_delete_binding` must always be `true` if the pattern is `Depth`.  (Line 107)

2021-05-17 14:56 UTC, mshinwell approved these changes

2021-05-17 15:01 UTC, merged